name: React App Workflow

on: [push]

jobs:
  Build-the-app:
    runs-on: ubuntu-latest

    steps:
      - name: step 1 checkout the repo
        uses: actions/checkout@v1

      - name: step 2 - Install node.js version 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'



      - name: step3- check node version and install dependencies
        run: |
          node --version
          npm ci
      - name: step4  build the app
        run: npm run build

      - name: Print output
        run: |
          echo "Build successful"
          echo "Ready to Deploy"
    
    

